use_frameworks!

target 'CrowdinSDK_Example' do
  pod 'CrowdinSDK', :path => '../', :testspecs => ['Core_Tests', 'CrowdinProvider_Tests', 'CrowdinAPI_Tests']
  pod 'CrowdinSDK/Screenshots', :path => '../'
  pod 'CrowdinSDK/IntervalUpdate', :path => '../'
  pod 'CrowdinSDK/RealtimeUpdate', :path => '../'
  pod 'CrowdinSDK/RefreshLocalization', :path => '../'
  pod 'CrowdinSDK/Settings', :path => '../'
  
  pod 'SwiftLint'
  pod 'FileBrowser', :git => 'https://github.com/serhii-londar/FileBrowser.git'
  pod 'FAPanels'
  pod 'R.swift'
  
  
  target 'CrowdinSDK_Tests' do
    inherit! :search_paths
  end
end
